CREATE DATABASE AT5;


CREATE TABLE TabelaEX ( NOME VARCHAR(100) NULL);


CREATE TABLE TabelaFX ( NOME VARCHAR(100) NULL);


INSERT INTO TabelaEX (NOME)
VALUES ('João');


INSERT INTO TabelaEX (NOME)
VALUES ('Maria');


INSERT INTO TabelaEX (NOME)
VALUES ('Pedro');


INSERT INTO TabelaEX (NOME)
VALUES ('Ana');


INSERT INTO TabelaEX (NOME)
VALUES ('Carlos');


INSERT INTO TabelaFX (NOME)
VALUES ('Luisa');


INSERT INTO TabelaFX (NOME)
VALUES ('Miguel');


INSERT INTO TabelaFX (NOME)
VALUES ('Sofia');


INSERT INTO TabelaFX (NOME)
VALUES ('Rafael');


INSERT INTO TabelaFX (NOME)
VALUES ('Isabela');


SELECT EX.NOME,
       FX.NOME
FROM TabelaEx AS EX
INNER JOIN TabelaFX AS FX ON EX.NOME = FX.NOME

SELECT EX.NOME,
       FX.NOME
FROM TabelaEx AS EX
LEFT JOIN TabelaFX AS FX ON EX.NOME = FX.NOME

SELECT EX.NOME,
       FX.NOME
FROM TabelaEx AS EX
RIGHT JOIN TabelaFX AS FX ON EX.NOME = FX.NOME

SELECT EX.NOME,
       FX.NOME
FROM TabelaEx AS EX
LEFT JOIN TabelaFX AS FX ON EX.NOME = FX.NOME
WHERE FX.NOME IS NULL

SELECT EX.NOME,
       FX.NOME
FROM TabelaEx AS EX
RIGHT JOIN TabelaFX AS FX ON EX.NOME = FX.NOME
WHERE FX.NOME IS NULL

SELECT * FROM TabelaEx;